# Etapa 1: Compilación de Angular
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration production

# Etapa 2: Servidor Web Nginx
FROM nginx:alpine
# Reemplaza la configuración por defecto de Nginx con la configuración SPA
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copia los archivos estáticos compilados de Angular
COPY --from=build /app/dist/app-login/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]